import { createRouter, createWebHashHistory } from 'vue-router'

const routes = [
  { path: '/login', component: () => import('@/views/login.vue'), meta: { layout: 'empty', title: '登录' } },
  { path: '/register', component: () => import('@/views/register.vue'), meta: { layout: 'empty', title: '注册' } },
  { path: '/', redirect: '/home' },
  { path: '/home', name: 'Home', component: () => import('@/views/home/index.vue'), meta: { title: '首页', breadcrumb: ['首页'], prdUrl: 'prd-home-pcard-activity-join.html', prdTitle: '首页 - PCard 活动参与弹窗 - PRD' } },
  { path: '/kanban', component: () => import('../views/kanban.vue'), meta: { title: '需求看板', breadcrumb: ['需求看板'] } },
  { path: '/history-kanban', component: () => import('../views/history-kanban.vue'), meta: { title: '历史需求记录', breadcrumb: ['历史需求记录'] } },
  
  // 自定义复杂页面
  {
    path: '/crm/change-detail', name: 'ChangeDetail', component: () => import('@/views/crm/change-detail.vue'),
    meta: { title: '客户变动明细', breadcrumb: ['客户管理', '客户变动明细'], prdUrl: 'prd-customer-change-detail.html', prdTitle: '客户变动详情 - PRD' }
  },
  {
    path: '/activity/pcard', name: 'Pcard', component: () => import('@/views/activity/Pcard.vue'),
    meta: { title: 'Pcard 银行卡活动详情', breadcrumb: ['活动管理', 'Pcard活动'], prdUrl: 'prd-pcard-detail.html', prdTitle: 'Pcard 详情与数据 - PRD' }
  },

  // 自动迁移页面
  { path: '/fund/deposit', component: () => import('@/views/fund/deposit.vue'), meta: { title: '入金', breadcrumb: ['出入金', '入金'] } },
  { path: '/fund/withdraw', component: () => import('@/views/fund/withdraw.vue'), meta: { title: '出金', breadcrumb: ['出入金', '出金'] } },
  { path: '/fund/commission-withdraw', component: () => import('@/views/fund/commission-withdraw.vue'), meta: { title: '返佣提现', breadcrumb: ['出入金', '返佣提现'] } },
  { path: '/fund/my-bonus', component: () => import('@/views/fund/my-bonus.vue'), meta: { title: '我的赠金', breadcrumb: ['出入金', '我的赠金'] } },
  { path: '/fund/audit-deposit', component: () => import('@/views/fund/audit-deposit.vue'), meta: { title: '待审核入金', breadcrumb: ['出入金', '待审核入金'] } },
  { path: '/fund/audit-withdraw', component: () => import('@/views/fund/audit-withdraw.vue'), meta: { title: '待审核出金', breadcrumb: ['出入金', '待审核出金'] } },
  { path: '/fund/audit-bonus', component: () => import('@/views/fund/audit-bonus.vue'), meta: { title: '赠金审核', breadcrumb: ['出入金', '赠金审核'] } },
  { path: '/fund/audit-bankcard', component: () => import('@/views/fund/audit-bankcard.vue'), meta: { title: '待审核银行卡', breadcrumb: ['出入金', '待审核银行卡'] } },
  { path: '/fund/internal-transfer', component: () => import('@/views/fund/internal-transfer.vue'), meta: { title: '内部转账', breadcrumb: ['出入金', '内部转账'] } },
  { path: '/fund/audit-transfer', component: () => import('@/views/fund/audit-transfer.vue'), meta: { title: '转账审核', breadcrumb: ['出入金', '转账审核'] } },
  { path: '/reconciliation/daily-record', component: () => import('@/views/reconciliation/daily-record.vue'), meta: { title: '每日对账日志', breadcrumb: ['财务对账', '每日对账日志'] } },
  { path: '/reconciliation/internal', component: () => import('@/views/reconciliation/internal.vue'), meta: { title: '对账异常看板', breadcrumb: ['财务对账', '对账异常看板'] } },
  { path: '/commission/basic-template', component: () => import('@/views/commission/basic-template.vue'), meta: { title: '基础分佣模版', breadcrumb: ['佣金管理', '基础分佣模版'] } },
  { path: '/commission/config', component: () => import('@/views/commission/config.vue'), meta: { title: '佣金配置', breadcrumb: ['佣金管理', '佣金配置'] } },
  { path: '/commission/basic-config', component: () => import('@/views/commission/basic-config.vue'), meta: { title: '基础分佣配置', breadcrumb: ['佣金管理', '基础分佣配置'] } },
  { path: '/commission/markup-config', component: () => import('@/views/commission/markup-config.vue'), meta: { title: '加点分佣配置', breadcrumb: ['佣金管理', '加点分佣配置'] } },
  { path: '/activity/list', component: () => import('@/views/activity/list.vue'), meta: { title: '活动列表', breadcrumb: ['活动管理', '活动列表'] } },
  { path: '/activity/growth', component: () => import('@/views/activity/growth.vue'), meta: { title: '成长计划', breadcrumb: ['活动管理', '成长计划'] } },
  { path: '/activity/ib', component: () => import('@/views/activity/ib.vue'), meta: { title: 'IB 计划', breadcrumb: ['活动管理', 'IB 计划'] } },
  { path: '/activity/audit', component: () => import('@/views/activity/audit.vue'), meta: { title: '活动审核', breadcrumb: ['活动管理', '活动审核'] } },
  { path: '/news/group', component: () => import('@/views/news/group.vue'), meta: { title: '集团动态', breadcrumb: ['动态公告', '集团动态'] } },
  { path: '/news/latest', component: () => import('@/views/news/latest.vue'), meta: { title: '最新公告', breadcrumb: ['动态公告', '最新公告'] } },
  { path: '/news/push', component: () => import('@/views/news/push.vue'), meta: { title: '推送消息', breadcrumb: ['动态公告', '推送消息'] } },
  { path: '/crm/list', component: () => import('@/views/crm/list.vue'), meta: { title: '客户列表', breadcrumb: ['客户管理', '客户列表'] } },
  { path: '/crm/account', component: () => import('@/views/crm/account.vue'), meta: { title: '账户管理', breadcrumb: ['客户管理', '账户管理'] } },
  { path: '/crm/audit', component: () => import('@/views/crm/audit.vue'), meta: { title: '账户审核', breadcrumb: ['客户管理', '账户审核'] } },
  { path: '/crm/group', component: () => import('@/views/crm/group.vue'), meta: { title: '分组管理', breadcrumb: ['客户管理', '分组管理'] } },
  { path: '/crm/share', component: () => import('@/views/crm/share.vue'), meta: { title: '分享链接', breadcrumb: ['客户管理', '分享链接'] } },
  { path: '/crm/sales', component: () => import('@/views/crm/sales.vue'), meta: { title: '销售列表', breadcrumb: ['客户管理', '销售列表'] } },
  { path: '/crm/leads', component: () => import('@/views/crm/leads.vue'), meta: { title: '留资列表', breadcrumb: ['客户管理', '留资列表'] } },
  { path: '/report/commission-stats', component: () => import('@/views/report/commission-stats.vue'), meta: { title: '佣金统计', breadcrumb: ['报表中心', '佣金统计'] } },
  { path: '/report/trading', component: () => import('@/views/report/trading.vue'), meta: { title: '交易报表', breadcrumb: ['报表中心', '交易报表'] } },
  { path: '/report/position', component: () => import('@/views/report/position.vue'), meta: { title: '持仓报表', breadcrumb: ['报表中心', '持仓报表'] } },
  { path: '/report/close-trade', component: () => import('@/views/report/close-trade.vue'), meta: { title: '平仓交易记录', breadcrumb: ['报表中心', '平仓交易记录'] } },
  { path: '/report/finance', component: () => import('@/views/report/finance.vue'), meta: { title: '财务报表', breadcrumb: ['报表中心', '财务报表'] } },
  { path: '/report/commission-report', component: () => import('@/views/report/commission-report.vue'), meta: { title: '佣金报表', breadcrumb: ['报表中心', '佣金报表'] } },
  { path: '/report/position-stats', component: () => import('@/views/report/position-stats.vue'), meta: { title: '持仓统计', breadcrumb: ['报表中心', '持仓统计'] } },
  { path: '/report/trade-record', component: () => import('@/views/report/trade-record.vue'), meta: { title: '交易记录', breadcrumb: ['报表中心', '交易记录'] } },
  { path: '/report/sales-trading', component: () => import('@/views/report/sales-trading.vue'), meta: { title: '销售交易奖励报表', breadcrumb: ['报表中心', '销售交易奖励报表'] } },
  { path: '/report/sales-deposit', component: () => import('@/views/report/sales-deposit.vue'), meta: { title: '销售入金奖励统计', breadcrumb: ['报表中心', '销售入金奖励统计'] } },
  { path: '/report/activity-join', component: () => import('@/views/report/activity-join.vue'), meta: { title: '活动参与报表', breadcrumb: ['报表中心', '活动参与报表'], prdUrl: 'prd-report-activity-join.html', prdTitle: '报表中心 - 活动参与报表 - PRD' } },
  { path: '/report/equity', component: () => import('@/views/report/equity.vue'), meta: { title: '盈亏报表', breadcrumb: ['报表中心', '盈亏报表'] } },
  { path: '/trust/phase1', component: () => import('@/views/trust/phase1.vue'), meta: { title: '委托交易一期', breadcrumb: ['委托交易', '委托交易一期'] } },
  { path: '/trust/account', component: () => import('@/views/trust/account.vue'), meta: { title: '委托交易账户管理', breadcrumb: ['委托交易', '委托交易账户管理'] } },
  { path: '/trust/rule-config', component: () => import('@/views/trust/rule-config.vue'), meta: { title: '查看规则配置', breadcrumb: ['委托交易', '查看规则配置'] } },
  { path: '/system/settings', component: () => import('@/views/system/settings.vue'), meta: { title: '系统设置', breadcrumb: ['系统管理', '系统设置'] } },
  { path: '/system/mt-settings', component: () => import('@/views/system/mt-settings.vue'), meta: { title: 'MT设置', breadcrumb: ['系统管理', 'MT设置'] } },
  { path: '/system/mass-msg', component: () => import('@/views/system/mass-msg.vue'), meta: { title: '群发管理', breadcrumb: ['系统管理', '群发管理'] } },
  { path: '/system/msg', component: () => import('@/views/system/msg.vue'), meta: { title: '消息管理', breadcrumb: ['系统管理', '消息管理'] } },
  { path: '/system/logs', component: () => import('@/views/system/logs.vue'), meta: { title: '日志管理', breadcrumb: ['系统管理', '日志管理'] } },
  { path: '/system/params', component: () => import('@/views/system/params.vue'), meta: { title: '配置参数', breadcrumb: ['系统管理', '配置参数'] } },
  { path: '/system/currency', component: () => import('@/views/system/currency.vue'), meta: { title: '支付币种', breadcrumb: ['系统管理', '支付币种'] } },
  { path: '/system/payment', component: () => import('@/views/system/payment.vue'), meta: { title: '支付管理', breadcrumb: ['系统管理', '支付管理'] } },
  { path: '/system/withdraw-settings', component: () => import('@/views/system/withdraw-settings.vue'), meta: { title: '提现设置', breadcrumb: ['系统管理', '提现设置'] } },
  { path: '/system/commission-settings', component: () => import('@/views/system/commission-settings.vue'), meta: { title: '返佣设置', breadcrumb: ['系统管理', '返佣设置'] } },
  { path: '/system/sms-logs', component: () => import('@/views/system/sms-logs.vue'), meta: { title: '验证码记录', breadcrumb: ['系统管理', '验证码记录'] } },
  { path: '/system/tags', component: () => import('@/views/system/tags.vue'), meta: { title: '标签管理', breadcrumb: ['系统管理', '标签管理'] } },
  { path: '/tools', component: () => import('@/views/tools.vue'), meta: { title: '交易工具', breadcrumb: ['交易工具'] } },
  { path: '/finance-management/report-detail', component: () => import('@/views/finance-management/report-detail.vue'), meta: { title: '财务报表明细', breadcrumb: ['财务管理', '财务报表明细'] } },
  { path: '/finance-management/client-info', component: () => import('@/views/finance-management/client-info.vue'), meta: { title: '客户信息表', breadcrumb: ['财务管理', '客户信息表'] } },
  { path: '/risk/login-logs', component: () => import('@/views/risk/login-logs.vue'), meta: { title: '客户登录日志', breadcrumb: ['风控管理', '客户登录日志'] } },
  { path: '/risk/ip-alert', component: () => import('@/views/risk/ip-alert.vue'), meta: { title: '登录 IP 一致性比对', breadcrumb: ['风控管理', '登录 IP 一致性比对'] } },
  { path: '/risk/blacklist', component: () => import('@/views/risk/blacklist.vue'), meta: { title: '黑名单管理', breadcrumb: ['风控管理', '黑名单管理'] } },
  { path: '/risk/close-interval', component: () => import('@/views/risk/close-interval.vue'), meta: { title: '平仓间隔统计', breadcrumb: ['风控管理', '平仓间隔统计'] } },


  // 补充遗漏的子页面
  { path: '/crm/client-product-list', component: () => import('@/views/crm/client-product-list.vue'), meta: { title: '智能交易系统', breadcrumb: ['智能交易系统'] } },
  { path: '/report/pnl-2', component: () => import('@/views/report/pnl-2.vue'), meta: { title: 'HATC CRM - 盈亏报表', breadcrumb: ['HATC CRM - 盈亏报表'] } },
  { path: '/crm/client-deposit-cent-account', component: () => import('@/views/crm/client-deposit-cent-account.vue'), meta: { title: '入金 - 美分账户原型', breadcrumb: ['入金 - 美分账户原型'] } },
  { path: '/activity/bonus-list', component: () => import('@/views/activity/bonus-list.vue'), meta: { title: 'HATC CRM - 注册赠金活动列表', breadcrumb: ['HATC CRM - 注册赠金活动列表'] } },
  { path: '/crm/client-withdraw-apply-cent-account', component: () => import('@/views/crm/client-withdraw-apply-cent-account.vue'), meta: { title: '出金', breadcrumb: ['出金'] } },
  { path: '/activity/growth-detail', component: () => import('@/views/activity/growth-detail.vue'), meta: { title: 'HATC CRM - 成长计划详情', breadcrumb: ['HATC CRM - 成长计划详情'] } },
  { path: '/activity/ib-detail', component: () => import('@/views/activity/ib-detail.vue'), meta: { title: 'HATC CRM - IB计划详情', breadcrumb: ['HATC CRM - IB计划详情'] } },
  { path: '/report/real-position', component: () => import('@/views/report/real-position.vue'), meta: { title: 'HATC CRM - 现实持仓报表', breadcrumb: ['HATC CRM - 现实持仓报表'] } },
  { path: '/news/list', component: () => import('@/views/news/list.vue'), meta: { title: '集团动态列表管理', breadcrumb: ['集团动态列表管理'] } },
  { path: '/product/orders', component: () => import('@/views/product/orders.vue'), meta: { title: '商品订单 - HATC CRM - 后台管理系统', breadcrumb: ['商品订单 - HATC CRM - 后台管理系统'] } },
  { path: '/report/profit', component: () => import('@/views/report/profit.vue'), meta: { title: 'HATC CRM - 盈亏报表', breadcrumb: ['HATC CRM - 盈亏报表'] } },
  { path: '/crm/client-my-orders', component: () => import('@/views/crm/client-my-orders.vue'), meta: { title: '我的智能交易系统订单', breadcrumb: ['我的智能交易系统订单'] } },
  { path: '/fund/deposit-pending-review', component: () => import('@/views/fund/deposit-pending-review.vue'), meta: { title: 'HATC CRM - 待审核入金', breadcrumb: ['HATC CRM - 待审核入金'] } },
  { path: '/crm/audit', component: () => import('@/views/crm/audit.vue'), meta: { title: 'HATC CRM - 开户审核详情', breadcrumb: ['HATC CRM - 开户审核详情'] } },
  { path: '/trust/group-config', component: () => import('@/views/trust/group-config.vue'), meta: { title: '委托交易分组配置', breadcrumb: ['委托交易分组配置'] } },
  { path: '/crm/sales-detail', component: () => import('@/views/crm/sales-detail.vue'), meta: { title: '新增销售', breadcrumb: ['新增销售'] } },
  { path: '/activity/cent-detail', component: () => import('@/views/activity/cent-detail.vue'), meta: { title: 'HATC CRM - 美分活动配置展示', breadcrumb: ['HATC CRM - 美分活动配置展示'] } },
  { path: '/crm/commission-audit-log', component: () => import('@/views/crm/commission-audit-log.vue'), meta: { title: 'HATC CRM - 对账记录', breadcrumb: ['HATC CRM - 对账记录'] } },
  { path: '/news/config-modes', component: () => import('@/views/news/config-modes.vue'), meta: { title: '集团动态后台完整配置（三模式）', breadcrumb: ['集团动态后台完整配置（三模式）'] } },
  { path: '/other/cockpit', component: () => import('@/views/other/cockpit.vue'), meta: { title: 'HATC CRM - 经营驾驶舱', breadcrumb: ['HATC CRM - 经营驾驶舱'] } },
  { path: '/crm/commission-daily-audit', component: () => import('@/views/crm/commission-daily-audit.vue'), meta: { title: 'HATC CRM - 佣金每日对账', breadcrumb: ['HATC CRM - 佣金每日对账'] } },
  { path: '/crm/client-withdraw-cent-account', component: () => import('@/views/crm/client-withdraw-cent-account.vue'), meta: { title: '出金管理 - 美分账户原型', breadcrumb: ['出金管理 - 美分账户原型'] } },
  { path: '/news/create-optimized', component: () => import('@/views/news/create-optimized.vue'), meta: { title: '集团动态创建优化版', breadcrumb: ['集团动态创建优化版'] } },
  { path: '/crm/account-mt-open', component: () => import('@/views/crm/account-mt-open.vue'), meta: { title: 'HATC CRM - 申请MT账户', breadcrumb: ['HATC CRM - 申请MT账户'] } },
  { path: '/crm/account-management-cent-account', component: () => import('@/views/crm/account-management-cent-account.vue'), meta: { title: 'HATC CRM - 账户管理', breadcrumb: ['HATC CRM - 账户管理'] } },
  { path: '/crm/sales-add', component: () => import('@/views/crm/sales-add.vue'), meta: { title: '新增销售', breadcrumb: ['新增销售'] } },
  { path: '/crm/withdraw-audit-detail', component: () => import('@/views/crm/withdraw-audit-detail.vue'), meta: { title: 'HATC CRM - 出金审核详情', breadcrumb: ['HATC CRM - 出金审核详情'] } },
  { path: '/crm/leads-detail', component: () => import('@/views/crm/leads-detail.vue'), meta: { title: 'HATC CRM - 留资列表', breadcrumb: ['HATC CRM - 留资列表'] } },
  { path: '/activity/bonus-detail', component: () => import('@/views/activity/bonus-detail.vue'), meta: { title: 'HATC CRM - 注册送赠金活动详情', breadcrumb: ['HATC CRM - 注册送赠金活动详情'] } },
  { path: '/report/customer-cent-account', component: () => import('@/views/report/customer-cent-account.vue'), meta: { title: 'HATC CRM - 客户报表', breadcrumb: ['HATC CRM - 客户报表'] } },
  { path: '/report/real-position-detail', component: () => import('@/views/report/real-position-detail.vue'), meta: { title: '交易品种持仓明细', breadcrumb: ['交易品种持仓明细'] } },
  { path: '/other/batch-mt-password-reset', component: () => import('@/views/other/batch-mt-password-reset.vue'), meta: { title: 'HATC CRM - 批量修改MT密码', breadcrumb: ['HATC CRM - 批量修改MT密码'] } },
  { path: '/product/management', component: () => import('@/views/product/management.vue'), meta: { title: '商品订单 - HATC CRM - 后台管理系统', breadcrumb: ['商品订单 - HATC CRM - 后台管理系统'] } },
  { path: '/commission/config', component: () => import('@/views/commission/config.vue'), meta: { title: 'HATC CRM - 代理佣金配置', breadcrumb: ['HATC CRM - 代理佣金配置'] } },
  { path: '/fund/payment-management', component: () => import('@/views/fund/payment-management.vue'), meta: { title: 'HATC CRM - 支付管理', breadcrumb: ['HATC CRM - 支付管理'] } },
  { path: '/fund/internal-transfer-record', component: () => import('@/views/fund/internal-transfer-record.vue'), meta: { title: 'HATC CRM - 内部转账', breadcrumb: ['HATC CRM - 内部转账'] } },
  { path: '/crm/sales-edit', component: () => import('@/views/crm/sales-edit.vue'), meta: { title: '新增销售', breadcrumb: ['新增销售'] } },
  { path: '/crm/client-withdraw-apply-commission', component: () => import('@/views/crm/client-withdraw-apply-commission.vue'), meta: { title: '出金', breadcrumb: ['出金'] } },
  { path: '/crm/client-detail', component: () => import('@/views/crm/client-detail.vue'), meta: { title: 'HATC CRM - 客户详情', breadcrumb: ['HATC CRM - 客户详情'] } },
  { path: '/product/edit', component: () => import('@/views/product/edit.vue'), meta: { title: '商品编辑 - HATC CRM - 后台管理系统', breadcrumb: ['商品编辑 - HATC CRM - 后台管理系统'] } },
  { path: '/report/pnl-1', component: () => import('@/views/report/pnl-1.vue'), meta: { title: 'HATC CRM - 盈亏报表', breadcrumb: ['HATC CRM - 盈亏报表'] } },
]

const router = createRouter({
  history: createWebHashHistory(),
  routes,
  scrollBehavior() {
    return { left: 0, top: 0 }
  }
})

export default router
