import { createRouter, createWebHashHistory } from 'vue-router'

const routes = [
  { path: '/login', component: () => import('@/views/login.vue'), meta: { layout: 'empty', title: '登录' } },
  { path: '/register', component: () => import('@/views/register.vue'), meta: { layout: 'empty', title: '注册' } },
  { path: '/profile-fill', component: () => import('@/views/profile-fill.vue'), meta: { title: '资料补全', breadcrumb: ['资料补全'], prdUrl: 'prd-overseas-id-check.html', prdTitle: '海外身份校验 - PRD' } },
  { path: '/', redirect: '/home' },
  { path: '/home', name: 'Home', component: () => import('@/views/home/index.vue'), meta: { title: '首页', breadcrumb: ['首页'], prdUrl: 'prd-home-pcard-activity-join.html', prdTitle: '首页 - PCard 活动参与弹窗 - PRD' } },
  { path: '/direct-home', name: 'DirectHome', component: () => import('@/views/direct-home.vue'), meta: { title: '首页', breadcrumb: ['首页'] } },
  { path: '/agent-home', name: 'AgentHome', component: () => import('@/views/agent-home.vue'), meta: { title: '代理首页', breadcrumb: ['代理首页'], prdUrl: 'prd-agent-home.html', prdTitle: '代理首页 - PRD' } },
  { path: '/kanban', component: () => import('../views/kanban.vue'), meta: { title: '需求看板', breadcrumb: ['需求看板'] } },
  { path: '/history-kanban', component: () => import('../views/history-kanban.vue'), meta: { title: '历史需求记录', breadcrumb: ['历史需求记录'] } },
  
  // 自定义复杂页面
  {
    path: '/crm/change-detail', name: 'ChangeDetail', component: () => import('@/views/crm/change-detail.vue'),
    meta: { title: '客户变动明细', breadcrumb: ['客户管理', '客户变动明细'], prdUrl: 'prd-customer-change-detail.html', prdTitle: '客户变动详情 - PRD' }
  },
  {
    path: '/activity/pcard', name: 'Pcard', component: () => import('@/views/activity/Pcard.vue'),
    meta: { title: 'Pcard 银行卡活动详情', breadcrumb: ['活动管理', 'Pcard活动'], prdUrl: 'prd-pcard-detail.html', prdTitle: 'Pcard 详情与数据 - PRD' }
  },
  {
    path: '/activity/pioneer-one-50000-detail',
    name: 'PioneerOne50000Detail',
    component: () => import('@/views/activity/pioneer-one-50000-detail.vue'),
    meta: { title: '先锋一号 50,000 USD 体验金活动详情', breadcrumb: ['活动管理', '活动列表', '先锋一号 50,000 USD 体验金活动'], prdUrl: 'prd-activity-pioneer-one-50000-release.html', prdTitle: '先锋一号 50,000 USD 体验金活动详情与盈利释放 - PRD' }
  },

  // 自动迁移页面
  { path: '/fund/deposit', component: () => import('@/views/fund/deposit.vue'), meta: { title: '入金', breadcrumb: ['出入金', '入金'] } },
  { path: '/fund/deposit-detail', component: () => import('@/views/fund/deposit-detail.vue'), meta: { title: '入金详情', breadcrumb: ['出入金', '入金', '入金详情'] } },
  { path: '/fund/withdraw', component: () => import('@/views/fund/withdraw.vue'), meta: { title: '出金', breadcrumb: ['出入金', '出金'] } },
  { path: '/fund/commission-withdraw', component: () => import('@/views/fund/commission-withdraw.vue'), meta: { title: '返佣提现', breadcrumb: ['出入金', '返佣提现'] } },
  { path: '/fund/my-bonus', component: () => import('@/views/fund/my-bonus.vue'), meta: { title: '我的赠金', breadcrumb: ['出入金', '我的赠金'] } },
  { path: '/fund/audit-deposit', redirect: '/fund/deposit-pending-review', meta: { title: '待审核入金', breadcrumb: ['出入金', '待审核入金'] } },
  { path: '/fund/audit-withdraw', component: () => import('@/views/fund/audit-withdraw.vue'), meta: { title: '待审核出金', breadcrumb: ['出入金', '待审核出金'] } },
  { path: '/fund/audit-bonus', component: () => import('@/views/fund/audit-bonus.vue'), meta: { title: '赠金审核', breadcrumb: ['出入金', '赠金审核'] } },
  { path: '/fund/audit-bankcard', component: () => import('@/views/fund/audit-bankcard.vue'), meta: { title: '待审核银行卡', breadcrumb: ['出入金', '待审核银行卡'] } },
  { path: '/fund/bankcard-add', component: () => import('@/views/fund/bankcard-add.vue'), meta: { title: '新增银行卡', breadcrumb: ['出入金', '新增银行卡'], prdUrl: 'prd-bankcard-add.html', prdTitle: '新增银行卡 - PRD' } },
  { path: '/fund/bankcard-detail', component: () => import('@/views/fund/bankcard-detail.vue'), meta: { title: '银行卡详情', breadcrumb: ['出入金', '待审核银行卡', '银行卡详情'] } },
  { path: '/fund/internal-transfer', component: () => import('@/views/fund/internal-transfer.vue'), meta: { title: '内部转账', breadcrumb: ['出入金', '内部转账'] } },
  { path: '/fund/audit-transfer', component: () => import('@/views/fund/audit-transfer.vue'), meta: { title: '转账审核', breadcrumb: ['出入金', '转账审核'] } },
  { path: '/reconciliation/daily-record', component: () => import('@/views/reconciliation/daily-record.vue'), meta: { title: '每日对账日志', breadcrumb: ['财务对账', '每日对账日志'] } },
  { path: '/reconciliation/internal', component: () => import('@/views/reconciliation/internal.vue'), meta: { title: '对账异常看板', breadcrumb: ['财务对账', '对账异常看板'] } },
  { path: '/commission/basic-template', component: () => import('@/views/commission/basic-template.vue'), meta: { title: '基础分佣模版', breadcrumb: ['佣金管理', '基础分佣模版'] } },
  { path: '/commission/config', component: () => import('@/views/commission/config.vue'), meta: { title: '佣金配置', breadcrumb: ['佣金管理', '佣金配置'] } },
  { path: '/commission/basic-config', component: () => import('@/views/commission/basic-config.vue'), meta: { title: '基础分佣配置', breadcrumb: ['佣金管理', '基础分佣配置'] } },
  { path: '/commission/markup-config', component: () => import('@/views/commission/markup-config.vue'), meta: { title: '加点分佣配置', breadcrumb: ['佣金管理', '加点分佣配置'] } },
  { path: '/commission/sales-list', component: () => import('@/views/commission/sales-list.vue'), meta: { title: '销售列表', breadcrumb: ['佣金管理', '销售列表'], prdUrl: 'prd-sales-differential-tier-rebate.html', prdTitle: '销售差异化阶梯返佣配置 - PRD' } },
  { path: '/commission/sales-list/create', component: () => import('@/views/commission/sales-create.vue'), meta: { title: '新增销售', breadcrumb: ['佣金管理', '销售列表', '新增销售'], prdUrl: 'prd-sales-differential-tier-rebate.html', prdTitle: '销售差异化阶梯返佣配置 - PRD' } },
  { path: '/activity/list', component: () => import('@/views/activity/list.vue'), meta: { title: '活动列表', breadcrumb: ['活动管理', '活动列表'] } },
  { path: '/activity/growth', component: () => import('@/views/activity/growth.vue'), meta: { title: '成长计划', breadcrumb: ['活动管理', '成长计划'] } },
  { path: '/activity/ib', component: () => import('@/views/activity/ib.vue'), meta: { title: 'IB 计划', breadcrumb: ['活动管理', 'IB 计划'] } },
  { path: '/activity/audit', component: () => import('@/views/activity/audit.vue'), meta: { title: '活动审核', breadcrumb: ['活动管理', '活动审核'], prdUrl: 'prd-activity-audit.html', prdTitle: '活动管理 - 活动审核（含先锋一号 50,000 USD 体验金活动）- PRD' } },
  { path: '/activity/participation-analysis', component: () => import('@/views/activity/participation-analysis.vue'), meta: { title: '活动参与分析', breadcrumb: ['活动管理', '活动参与分析'], prdUrl: 'prd-activity-participation-analysis.html', prdTitle: '活动参与分析 - PRD' } },
  { path: '/news/group', component: () => import('@/views/news/group.vue'), meta: { title: '集团动态', breadcrumb: ['动态公告', '集团动态'] } },
  { path: '/news/latest', component: () => import('@/views/news/latest.vue'), meta: { title: '最新公告', breadcrumb: ['动态公告', '最新公告'] } },
  { path: '/news/push', component: () => import('@/views/news/push.vue'), meta: { title: '推送消息', breadcrumb: ['动态公告', '推送消息'] } },
  { path: '/crm/list', component: () => import('@/views/crm/list.vue'), meta: { title: '客户列表', breadcrumb: ['客户管理', '客户列表'], prdUrl: 'prd-cent-account-page-client-list.html', prdTitle: '客户列表 - PRD' } },
  { path: '/crm/account', component: () => import('@/views/crm/account.vue'), meta: { title: '账户管理', breadcrumb: ['客户管理', '账户管理'], prdUrl: 'prd-cent-account-page-account-management.html', prdTitle: '账户管理 - PRD' } },
  { path: '/crm/account-detail', component: () => import('@/views/crm/account-detail.vue'), meta: { title: '账户详情', breadcrumb: ['客户管理', '账户管理', '账户详情'] } },
  { path: '/crm/audit-list', component: () => import('@/views/crm/audit-list.vue'), meta: { title: '账户审核', breadcrumb: ['客户管理', '账户审核'], prdUrl: 'prd-cent-account-page-audit-list.html', prdTitle: '账户审核列表 - PRD' } },
  { path: '/crm/group', component: () => import('@/views/crm/group.vue'), meta: { title: '分组管理', breadcrumb: ['客户管理', '分组管理'] } },
  { path: '/crm/share', component: () => import('@/views/crm/share.vue'), meta: { title: '分享链接', breadcrumb: ['客户管理', '分享链接'] } },
  { path: '/crm/sales', component: () => import('@/views/crm/sales.vue'), meta: { title: '销售列表', breadcrumb: ['客户管理', '销售列表'], prdUrl: 'prd-sales-list.html', prdTitle: '销售列表 - PRD' } },
  { path: '/crm/leads', component: () => import('@/views/crm/leads.vue'), meta: { title: '留资列表', breadcrumb: ['客户管理', '留资列表'], prdUrl: 'prd-leads-list.html', prdTitle: '留资列表 - PRD' } },
  { path: '/report/commission-stats', component: () => import('@/views/report/commission-stats.vue'), meta: { title: '佣金统计', breadcrumb: ['报表中心', '佣金统计'] } },
  { path: '/report/trading', component: () => import('@/views/report/trading.vue'), meta: { title: '交易报表', breadcrumb: ['报表中心', '交易报表'] } },
  { path: '/report/position', component: () => import('@/views/report/position.vue'), meta: { title: '持仓报表', breadcrumb: ['报表中心', '持仓报表'] } },
  { path: '/report/close-trade', component: () => import('@/views/report/close-trade.vue'), meta: { title: '平仓交易记录', breadcrumb: ['报表中心', '平仓交易记录'] } },
  { path: '/report/finance', component: () => import('@/views/report/finance.vue'), meta: { title: '财务报表', breadcrumb: ['报表中心', '财务报表'] } },
  { path: '/report/deposit-withdraw', component: () => import('@/views/report/deposit-withdraw.vue'), meta: { title: '出入金报表', breadcrumb: ['报表中心', '出入金报表'], prdUrl: 'prd-report-relation-tree-filter.html', prdTitle: '报表关系树筛选 - PRD' } },
  { path: '/report/withdraw-report', component: () => import('@/views/report/withdraw-report.vue'), meta: { title: '提现报表', breadcrumb: ['报表中心', '提现报表'], prdUrl: 'prd-report-relation-tree-filter.html', prdTitle: '报表关系树筛选 - PRD' } },
  { path: '/report/commission-report', component: () => import('@/views/report/commission-report.vue'), meta: { title: '佣金报表', breadcrumb: ['报表中心', '佣金报表'] } },
  { path: '/report/position-stats', component: () => import('@/views/report/position-stats.vue'), meta: { title: '持仓统计', breadcrumb: ['报表中心', '持仓统计'] } },
  { path: '/report/trade-record', component: () => import('@/views/report/trade-record.vue'), meta: { title: '交易记录', breadcrumb: ['报表中心', '交易记录'] } },
  { path: '/report/sales-trading', component: () => import('@/views/report/sales-trading.vue'), meta: { title: '销售交易奖励报表', breadcrumb: ['报表中心', '销售交易奖励报表'], prdUrl: 'prd-sales-trading-reward-report.html', prdTitle: '销售交易奖励报表 - PRD' } },
  { path: '/report/sales-deposit', component: () => import('@/views/report/sales-deposit.vue'), meta: { title: '销售入金奖励统计', breadcrumb: ['报表中心', '销售入金奖励统计'] } },
  { path: '/report/activity-join', component: () => import('@/views/report/activity-join.vue'), meta: { title: '活动参与报表', breadcrumb: ['报表中心', '活动参与报表'], prdUrl: 'prd-report-activity-join.html', prdTitle: '报表中心 - 活动参与报表 - PRD' } },
  { path: '/report/company-pnl', component: () => import('@/views/report/company-pnl.vue'), meta: { title: '公司盈亏报表', breadcrumb: ['报表中心', '公司盈亏报表'], prdUrl: 'prd-report-company-pnl.html', prdTitle: '报表中心 - 公司盈亏报表 - PRD' } },
  { path: '/report/equity', component: () => import('@/views/report/equity.vue'), meta: { title: '盈亏报表', breadcrumb: ['报表中心', '盈亏报表'] } },
  { path: '/trust/phase1', component: () => import('@/views/trust/phase1.vue'), meta: { title: '委托交易一期', breadcrumb: ['委托交易', '委托交易一期'] } },
  { path: '/trust/account', component: () => import('@/views/trust/account.vue'), meta: { title: '委托交易账户管理', breadcrumb: ['委托交易', '委托交易账户管理'] } },
  { path: '/trust/rule-config', component: () => import('@/views/trust/rule-config.vue'), meta: { title: '查看规则配置', breadcrumb: ['委托交易', '查看规则配置'] } },
  { path: '/system/settings', component: () => import('@/views/system/settings.vue'), meta: { title: '系统设置', breadcrumb: ['系统管理', '系统设置'] } },
  { path: '/system/mt-settings', component: () => import('@/views/system/mt-settings.vue'), meta: { title: 'MT设置', breadcrumb: ['系统管理', 'MT设置'] } },
  { path: '/system/mass-msg', component: () => import('@/views/system/mass-msg.vue'), meta: { title: '群发管理', breadcrumb: ['系统管理', '群发管理'] } },
  { path: '/system/msg', component: () => import('@/views/system/msg.vue'), meta: { title: '消息管理', breadcrumb: ['系统管理', '消息管理'] } },
  { path: '/system/logs', component: () => import('@/views/system/logs.vue'), meta: { title: '日志管理', breadcrumb: ['系统管理', '日志管理'] } },
  { path: '/system/params', component: () => import('@/views/system/params.vue'), meta: { title: '配置参数', breadcrumb: ['系统管理', '配置参数'] } },
  { path: '/system/currency', component: () => import('@/views/system/currency.vue'), meta: { title: '支付币种', breadcrumb: ['系统管理', '支付币种'] } },
  { path: '/system/payment', component: () => import('@/views/fund/payment-management.vue'), meta: { title: '支付设置', breadcrumb: ['系统管理', '支付设置'], prdUrl: 'prd-payment-management.html', prdTitle: '支付管理 - PRD' } },
  { path: '/system/withdraw-settings', component: () => import('@/views/system/withdraw-settings.vue'), meta: { title: '提现设置', breadcrumb: ['系统管理', '提现设置'], prdUrl: 'prd-withdraw-settings.html', prdTitle: '提现设置 - PRD' } },
  { path: '/system/commission-settings', component: () => import('@/views/system/commission-settings.vue'), meta: { title: '返佣设置', breadcrumb: ['系统管理', '返佣设置'] } },
  { path: '/system/sms-logs', component: () => import('@/views/system/sms-logs.vue'), meta: { title: '验证码记录', breadcrumb: ['系统管理', '验证码记录'] } },
  { path: '/system/tags', component: () => import('@/views/system/tags.vue'), meta: { title: '标签管理', breadcrumb: ['系统管理', '标签管理'] } },
  { path: '/tools', component: () => import('@/views/tools.vue'), meta: { title: '交易工具', breadcrumb: ['交易工具'] } },
  { path: '/finance-management/report-detail', component: () => import('@/views/finance-management/report-detail.vue'), meta: { title: '财务报表明细', breadcrumb: ['财务管理', '财务报表明细'] } },
  { path: '/finance-management/client-info', component: () => import('@/views/finance-management/client-info.vue'), meta: { title: '客户信息表', breadcrumb: ['财务管理', '客户信息表'] } },
  { path: '/risk/login-logs', component: () => import('@/views/risk/login-logs.vue'), meta: { title: '客户登录日志', breadcrumb: ['风控管理', '客户登录日志'] } },
  { path: '/risk/ip-alert', component: () => import('@/views/risk/ip-alert.vue'), meta: { title: '登录 IP 一致性比对', breadcrumb: ['风控管理', '登录 IP 一致性比对'] } },
  { path: '/risk/blacklist', component: () => import('@/views/risk/blacklist.vue'), meta: { title: '黑名单管理', breadcrumb: ['风控管理', '黑名单管理'] } },
  { path: '/risk/close-interval', component: () => import('@/views/risk/close-interval.vue'), meta: { title: '平仓间隔统计', breadcrumb: ['风控管理', '平仓间隔统计'] } },


  // 补充遗漏的子页面
  { path: '/crm/client-product-list', component: () => import('@/views/crm/client-product-list.vue'), meta: { title: '智能交易系统', breadcrumb: ['智能交易系统'], prdUrl: 'prd-product-list.html', prdTitle: '智能交易系统 - 商品列表 - PRD' } },
  { path: '/product/detail', component: () => import('@/views/product/detail.vue'), meta: { title: '商品详情', breadcrumb: ['智能交易系统', '商品详情'], prdUrl: 'prd-product-detail.html', prdTitle: '智能交易系统 - 商品详情及购买流程 - PRD' } },
  { path: '/report/pnl-2', component: () => import('@/views/report/pnl-2.vue'), meta: { title: 'HATC CRM - 盈亏报表', breadcrumb: ['HATC CRM - 盈亏报表'] } },
  { path: '/crm/client-deposit-cent-account', component: () => import('@/views/crm/client-deposit-cent-account.vue'), meta: { title: '入金 - 美分账户原型', breadcrumb: ['入金 - 美分账户原型'] } },
  { path: '/crm/client-deposit-record-cent-account', component: () => import('@/views/crm/client-deposit-record-cent-account.vue'), meta: { title: '入金记录', breadcrumb: ['出入金', '入金记录'], prdUrl: 'prd-cent-account-page-deposit-record.html', prdTitle: '入金列表 - PRD' } },
  { path: '/crm/client-withdraw-record-cent-account', component: () => import('@/views/crm/client-withdraw-record-cent-account.vue'), meta: { title: '出金记录', breadcrumb: ['出入金', '出金记录'], prdUrl: 'prd-cent-account-page-withdraw-record.html', prdTitle: '出金列表 - PRD' } },
  { path: '/activity/bonus-list', component: () => import('@/views/activity/bonus-list.vue'), meta: { title: 'HATC CRM - 注册赠金活动列表', breadcrumb: ['HATC CRM - 注册赠金活动列表'] } },
  { path: '/crm/client-withdraw-apply-cent-account', component: () => import('@/views/crm/client-withdraw-apply-cent-account.vue'), meta: { title: '出金', breadcrumb: ['出金'] } },
  { path: '/activity/growth-detail', component: () => import('@/views/activity/growth-detail.vue'), meta: { title: 'HATC CRM - 成长计划详情', breadcrumb: ['HATC CRM - 成长计划详情'] } },
  { path: '/activity/ib-detail', component: () => import('@/views/activity/ib-detail.vue'), meta: { title: 'HATC CRM - IB计划详情', breadcrumb: ['HATC CRM - IB计划详情'] } },
  { path: '/report/real-position', component: () => import('@/views/report/real-position.vue'), meta: { title: '现实持仓报表', breadcrumb: ['报表中心', '现实持仓报表'], prdUrl: 'prd-report-relation-tree-filter.html', prdTitle: '报表关系树筛选 - PRD' } },
  { path: '/news/list', component: () => import('@/views/news/list.vue'), meta: { title: '集团动态列表管理', breadcrumb: ['集团动态列表管理'] } },
  { path: '/product/orders', component: () => import('@/views/product/orders.vue'), meta: { title: '商品订单管理', breadcrumb: ['商品管理', '订单管理'], prdUrl: 'prd-admin-product-orders.html', prdTitle: '后台商品订单管理 - PRD' } },
  { path: '/report/profit', component: () => import('@/views/report/profit.vue'), meta: { title: 'HATC CRM - 盈亏报表', breadcrumb: ['HATC CRM - 盈亏报表'] } },
  { path: '/crm/client-my-orders', component: () => import('@/views/crm/client-my-orders.vue'), meta: { title: '我的智能交易系统订单', breadcrumb: ['我的智能交易系统订单'], prdUrl: 'prd-client-my-orders.html', prdTitle: '智能交易系统 - 客户端我的订单 - PRD' } },
  { path: '/fund/deposit-pending-review', component: () => import('@/views/fund/deposit-pending-review.vue'), meta: { title: '待审核入金', breadcrumb: ['出入金', '待审核入金'], prdUrl: 'prd-admin-deposit.html', prdTitle: '管理员入金 - PRD' } },
  { path: '/crm/audit', component: () => import('@/views/crm/audit.vue'), meta: { title: '开户审核详情', breadcrumb: ['客户管理', '账户审核', '开户审核详情'], prdUrl: 'prd-cent-account-page-audit-detail.html', prdTitle: '开户审核详情 - PRD' } },
  { path: '/trust/group-config', component: () => import('@/views/trust/group-config.vue'), meta: { title: '委托交易分组配置', breadcrumb: ['委托交易分组配置'] } },
  { path: '/crm/sales-detail', component: () => import('@/views/crm/sales-detail.vue'), meta: { title: '销售详情', breadcrumb: ['客户管理', '销售列表', '销售详情'] } },
  { path: '/activity/cent-detail', component: () => import('@/views/activity/cent-detail.vue'), meta: { title: 'HATC CRM - 美分活动配置展示', breadcrumb: ['HATC CRM - 美分活动配置展示'] } },
  { path: '/crm/commission-audit-log', component: () => import('@/views/crm/commission-audit-log.vue'), meta: { title: 'HATC CRM - 对账记录', breadcrumb: ['HATC CRM - 对账记录'] } },
  { path: '/news/config-modes', component: () => import('@/views/news/config-modes.vue'), meta: { title: '集团动态后台完整配置（三模式）', breadcrumb: ['集团动态后台完整配置（三模式）'] } },
  { path: '/other/login-register', component: () => import('@/views/other/login-register.vue'), meta: { title: '新版登录注册', breadcrumb: ['其他页面', '新版登录注册'] } },
  { path: '/other/cockpit', component: () => import('@/views/other/cockpit.vue'), meta: { title: 'HATC CRM - 经营驾驶舱', breadcrumb: ['HATC CRM - 经营驾驶舱'] } },
  { path: '/crm/commission-daily-audit', component: () => import('@/views/crm/commission-daily-audit.vue'), meta: { title: 'HATC CRM - 佣金每日对账', breadcrumb: ['HATC CRM - 佣金每日对账'] } },
  { path: '/crm/client-withdraw-cent-account', component: () => import('@/views/crm/client-withdraw-cent-account.vue'), meta: { title: '出金管理 - 美分账户原型', breadcrumb: ['出金管理 - 美分账户原型'] } },
  { path: '/news/create-optimized', component: () => import('@/views/news/create-optimized.vue'), meta: { title: '集团动态创建优化版', breadcrumb: ['集团动态创建优化版'] } },
  { path: '/crm/account-mt-open', component: () => import('@/views/crm/account-mt-open.vue'), meta: { title: '申请MT账户', breadcrumb: ['客户管理', '账户管理', '申请MT账户'], prdUrl: 'prd-account-mt-open.html', prdTitle: '申请MT账户 - PRD' } },
  { path: '/crm/account-management-cent-account', redirect: { path: '/crm/account', query: { accountType: 'cent' } } },
  { path: '/crm/sales-add', component: () => import('@/views/crm/sales-add.vue'), meta: { title: '新增销售', breadcrumb: ['客户管理', '销售列表', '新增销售'], prdUrl: 'prd-sales-add.html', prdTitle: '新增销售 - PRD' } },
  { path: '/crm/withdraw-audit-detail', component: () => import('@/views/crm/withdraw-audit-detail.vue'), meta: { title: '出金审核详情', breadcrumb: ['出入金', '待审核出金', '出金审核详情'], prdUrl: 'prd-cent-account-page-withdraw-audit-detail.html', prdTitle: '出金审核详情 - PRD' } },
  { path: '/crm/leads-detail', component: () => import('@/views/crm/leads-detail.vue'), meta: { title: '留资详情', breadcrumb: ['客户管理', '留资列表', '留资详情'], prdUrl: 'prd-leads-detail.html', prdTitle: '留资详情 - PRD' } },
  { path: '/activity/bonus-detail', component: () => import('@/views/activity/bonus-detail.vue'), meta: { title: 'HATC CRM - 注册送赠金活动详情', breadcrumb: ['HATC CRM - 注册送赠金活动详情'] } },
  { path: '/report/customer-cent-account', component: () => import('@/views/report/customer-cent-account.vue'), meta: { title: 'HATC CRM - 客户报表', breadcrumb: ['HATC CRM - 客户报表'] } },
  { path: '/report/real-position-detail', component: () => import('@/views/report/real-position-detail.vue'), meta: { title: '交易品种持仓明细', breadcrumb: ['交易品种持仓明细'] } },
  { path: '/other/batch-mt-password-reset', component: () => import('@/views/other/batch-mt-password-reset.vue'), meta: { title: 'HATC CRM - 批量修改MT密码', breadcrumb: ['HATC CRM - 批量修改MT密码'] } },
  { path: '/product/management', component: () => import('@/views/product/management.vue'), meta: { title: '商品管理列表', breadcrumb: ['商品管理'], prdUrl: 'prd-admin-product-management.html', prdTitle: '智能交易系统 - 后台商品管理列表 - PRD' } },
  { path: '/fund/payment-management', component: () => import('@/views/fund/payment-management.vue'), meta: { title: 'HATC CRM - 支付管理', breadcrumb: ['HATC CRM - 支付管理'] } },
  { path: '/fund/payment-config-records', component: () => import('@/views/fund/payment-config-records.vue'), meta: { title: '支付配置记录', breadcrumb: ['系统管理', '支付设置', '支付配置记录'], prdUrl: 'prd-payment-management.html', prdTitle: '支付设置 - 配置记录 - PRD' } },
  { path: '/fund/withdraw-config-records', component: () => import('@/views/fund/withdraw-config-records.vue'), meta: { title: '提现配置记录', breadcrumb: ['系统管理', '提现设置', '提现配置记录'], prdUrl: 'prd-withdraw-settings.html', prdTitle: '提现设置 - 配置记录 - PRD' } },
  { path: '/fund/internal-transfer-record', component: () => import('@/views/fund/internal-transfer-record.vue'), meta: { title: '内部转账记录', breadcrumb: ['出入金', '内部转账记录'], prdUrl: 'prd-internal-transfer-record.html', prdTitle: '内部转账记录 - PRD' } },
  { path: '/crm/sales-edit', component: () => import('@/views/crm/sales-edit.vue'), meta: { title: '编辑销售', breadcrumb: ['客户管理', '销售列表', '编辑销售'], prdUrl: 'prd-sales-add.html', prdTitle: '新增/编辑销售 - PRD' } },
  { path: '/crm/client-withdraw-apply-commission', component: () => import('@/views/crm/client-withdraw-apply-commission.vue'), meta: { title: '出金', breadcrumb: ['出金'] } },
  { path: '/crm/client-detail', component: () => import('@/views/crm/client-detail.vue'), meta: { title: '客户详情', breadcrumb: ['客户管理', '客户详情'], prdUrl: 'prd-client-detail.html', prdTitle: '客户详情 - PRD' } },
  { path: '/product/edit', component: () => import('@/views/product/edit.vue'), meta: { title: '商品编辑', breadcrumb: ['商品管理', '商品编辑'], prdUrl: 'prd-admin-product-edit.html', prdTitle: '智能交易系统 - 后台新增/编辑商品 - PRD' } },
  { path: '/report/pnl-1', component: () => import('@/views/report/pnl-1.vue'), meta: { title: 'HATC CRM - 盈亏报表', breadcrumb: ['HATC CRM - 盈亏报表'] } },
]

const router = createRouter({
  history: createWebHashHistory(),
  routes,
  scrollBehavior() {
    return { left: 0, top: 0 }
  }
})

export default router
